<?php
/**
 * App copy catalog — defaults from Flutter AppStrings + admin groups.
 *
 * @package RadioUdaanAppApi
 */

defined( 'ABSPATH' ) || exit;

/**
 * Central catalog for GET /config → copy.
 */
class RadioUdaan_App_Copy_Catalog {

	const OPTION_PREFIX = 'radioudaan_copy_';
	const OPTION_OVERRIDES = 'radioudaan_copy_overrides';

	/**
	 * @return array<string,string>
	 */
	public static function default_catalog() {
		return array(
			'about_us' => 'About Us',
			'about_us_subtitle' => 'Our story and vision',
			'about_whats_new' => "What's New",
			'about_whats_new_subtitle' => 'Announcements and community news',
			'about_options_intro' => '',
			'about_options_title' => 'About Radio Udaan',
			'accessibility_section' => 'Accessibility',
			'account_delete_failed' => 'Could not delete account',
			'account_deleted_signing_out' => 'Account deleted. Signing out',
			'account_icon' => 'Account',
			'app_logo_semantics' => 'Radio Udaan logo',
			'app_name' => 'Radio Udaan',
			'app_version_label' => 'Radio Udaan Version {version}',
			'back_button' => 'Back',
			'back_to_login' => 'Back to login',
			'bold_text' => 'Bold Text',
			'bold_text_hint' => 'Heavier text for easier reading',
			'bootstrap_loading' => 'READY TO LAUNCH',
			'bootstrap_offline' => 'Could not connect to the server. Check your network and try again.',
			'force_update_title' => 'Update required',
			'force_update_message' => 'This version of Radio Udaan is no longer supported. Please update to continue.',
			'force_update_current_build' => 'Your current build is {build}.',
			'force_update_button' => 'Update app',
			'branding_logo_semantics' => '{app_name} logo',
			'call_accessibility_helpline' => 'Call Accessibility Helpline',
			'cancel' => 'Cancel',
			'change_password_intro' => 'Keep your account secure with a strong password.',
			'change_password_title' => 'Change Password',
			'choose_file' => 'Choose file',
			'confirm_new_password' => 'Confirm New Password',
			'confirm_password_label' => 'Confirm password',
			'contact_form_intro' => 'Tell us what you need and our team will get back to you.',
			'contact_form_title' => 'Send us a message',
			'contact_support' => 'Contact Support',
			'contact_title' => 'Contact',
			'contact_email_subtitle' => 'Send us an email directly',
			'contact_email_title' => 'Contact Email',
			'contact_number_subtitle' => 'Call our accessibility helpline',
			'contact_number_title' => 'Contact Number',
			'copied_to_clipboard' => 'Copied to clipboard',
			'copy_value' => 'Copy',
			'create_account' => 'Create account',
			'current_password' => 'Current Password',
			'delete_account' => 'Delete account',
			'delete_account_confirm_body' => 'This permanently deletes your app login and signs you out. You can sign in again with your phone number.' . "\n\n" . 'Event registrations you already submitted are not removed.',
			'delete_account_confirm_title' => 'Delete account?',
			'delete_account_subtitle' => 'Removes your app login on our servers. Event registrations are not deleted.',
			'dont_have_account' => 'Don\'t have an account?',
			'donate_bank_details_title' => 'Bank Account Details',
			'donate_scan_caption' => 'Scan the QR code using any UPI app to support Radio Udaan.',
			'donate_scan_title' => 'Scan & Donate',
			'donate_us' => 'Donate Us',
			'donate_us_subtitle' => 'Support our mission online, UPI, or bank transfer',
			'donate_pay_online_title' => 'Pay Online',
			'donate_pay_online_subtitle' => 'Choose a donation amount, then donate securely. You can pick a suggested amount or type your own.',
			'donate_pay_online_subtitle_ios' => 'Choose a donation amount, then donate securely. You can pick a suggested amount or type your own. Opens Razorpay in Safari. After you pay, return here — we confirm automatically.',
			'donate_amount_heading' => 'Donation amounts. Pick one, or use the custom amount field below.',
			'donate_amount_chip_semantics' => '{amount} rupees',
			'donate_selected_summary' => 'You will donate {amount} rupees',
			'donate_amount_custom_label' => 'Custom amount in rupees',
			'donate_amount_custom_hint' => 'Optional. Type here to donate a different amount.',
			'donate_now_button' => 'Donate now',
			'donate_now_with_amount' => 'Donate now. You will donate {amount} rupees.',
			'donate_now_loading' => 'Donating, please wait',
			'donate_success_title' => 'Thank you for your donation',
			'donate_success_message' => 'Your payment was successful. Thank you for supporting Radio Udaan.',
			'donate_failed_message' => 'Payment could not be completed. Please try again.',
			'donate_80g_checkbox' => 'I want an 80G tax exemption receipt',
			'donate_80g_hint' => 'Includes Form 10BE tax receipt.',
			'donate_pan_label' => 'PAN',
			'donate_pan_required' => 'Enter a valid PAN to receive your 80G receipt.',
			'donate_form_10be_note' => 'Form 10BE for income tax filing will be issued by the trust as per Income Tax rules.',
			'donate_email_from_account' => 'Email, from your account, cannot edit',
			'donate_custom_amount_selected' => 'Custom amount {amount} rupees selected.',
			'donate_opening_payment' => 'Opening secure payment',
			'donate_opening_with_amount' => 'Donating {amount} rupees. Opening secure payment.',
			'donate_check_payment' => 'I completed payment',
			'donate_ios_waiting' => 'Waiting to confirm your payment. Return here after paying in Safari.',
			'donate_ios_confirming' => 'Confirming your payment',
			'donate_verifying' => 'Verifying your payment',
			'donate_back_to_donate' => 'Back to Donate',
			'donate_invalid_amount' => 'Enter a valid donation amount.',
			'edit_profile_title' => 'Edit Profile',
			'email_hint' => 'you@example.com',
			'email_invalid' => 'Enter a valid email address.',
			'email_label' => 'Email',
			'email_not_verified' => 'Email not verified',
			'email_support' => 'Email Support',
			'event_deep_link_loading' => 'Opening event registration',
			'event_deep_link_opening' => 'Opening registration for {event_title}',
			'event_registration_loading_form' => 'Loading registration form',
			'event_registration_retry_load' => 'Retry loading registration form',
			'event_registration_title' => 'Event Registration',
			'events_empty' => 'No open events right now.',
			'events_loading' => 'Loading events',
			'events_page_intro' => 'Join our vibrant community in upcoming accessible live streams and workshops.',
			'events_page_title' => 'Register For Events',
			'events_register_now' => 'Register Now',
			'events_registration_closed' => 'Registration closed',
			'forgot_password_channel_email' => 'Email',
			'forgot_password_channel_phone' => 'Mobile',
			'forgot_password_channel_semantics' => 'Choose email or mobile for password reset',
			'forgot_password_email_hint' => 'Enter your email',
			'forgot_password_email_note' => 'Reset codes are sent only to your verified email. Sign in and verify your email first if you have not already.',
			'forgot_password_help_body' => 'Need help? Call our 24/7 accessible support line or use the screen reader shortcut Alt + H.',
			'forgot_password_intro' => 'Reset your password using your email or mobile number.',
			'forgot_password_link' => 'Forgot Password?',
			'forgot_password_phone_note' => 'We\'ll text a one-time code to your verified mobile number, then you can choose a new password.',
			'forgot_password_success' => 'If an account exists, reset instructions have been sent.',
			'forgot_password_title' => 'Forgot Password',
			'follow_us' => 'Follow us',
			'has_account_link' => 'Already have an account? Sign in',
			'has_account_prompt' => 'Already have an account?',
			'help_and_contact' => 'Contact',
			'help_and_contact_subtitle' => 'Send a message to our team',
			'help_faq_topics' => 'How do I register for an event?
How do I listen to live radio?
How do I verify my email?
How do I change my password?
How do I delete my account?',
			'help_message' => 'Message',
			'help_search_hint' => 'Search FAQ or Support Topics',
			'help_subject' => 'Subject',
			'help_title' => 'How can we help?',
			'hide_password' => 'Hide password',
			'high_contrast_mode' => 'High Contrast Mode',
			'high_contrast_mode_hint' => 'Maximize visibility of interface elements',
			'identifier_hint' => 'you@example.com or mobile number',
			'identifier_invalid' => 'Enter a valid email address or mobile number.',
			'identifier_label' => 'Email or mobile',
			'join_community' => 'Join Community',
			'join_the_discussion' => 'Join the discussion',
			'join_whats_app_channel' => 'Join WhatsApp Channel',
			'label_account_name' => 'Account Name',
			'label_account_number' => 'Account Number',
			'label_bank_address' => 'Address',
			'label_bank_name' => 'Bank Name',
			'label_branch_name' => 'Branch Name',
			'label_ifsc' => 'IFSC Code',
			'label_micr' => 'MICR Code',
			'label_upi_id' => 'UPI ID',
			'legal_section' => 'Legal & account',
			'library_duration_prefix' => 'Duration: ',
			'library_embed_error' => 'This video could not play inside the app. Try opening it in YouTube.',
			'library_loading' => 'Loading library',
			'library_no_description' => 'No description available for this video.',
			'library_no_video' => 'This video cannot be played in the app right now.',
			'library_open_in_youtube' => 'Open in YouTube',
			'library_play_video' => 'Play video',
			'library_player_buffering' => 'Video buffering',
			'library_player_paused' => 'Video paused',
			'library_playlist_videos_empty' => 'This playlist has no videos yet.',
			'library_playlists' => 'Playlists',
			'library_playlists_empty' => 'No playlists available yet.',
			'library_saved_screen_title' => 'Saved',
			'library_saved_entry_subtitle' => 'Your favorite shows and saved videos',
			'library_saved_radio_section' => 'Radio shows',
			'library_saved_videos_section' => 'Videos',
			'library_saved_empty' => 'Nothing saved yet. Favorite a radio show or save a video to see it here.',
			'library_recent_uploads' => 'Recent Uploads',
			'library_recent_uploads_empty' => 'No recent uploads yet.',
			'library_save_video' => 'Save',
			'library_saved_video' => 'Saved',
			'library_search_clear' => 'Clear search',
			'library_search_cleared' => 'Search cleared',
			'library_search_empty' => 'No videos match your search.',
			'library_search_hint' => 'Type keywords...',
			'library_search_videos' => 'Search Videos',
			'library_shows' => 'Playlists',
			'library_shows_empty' => 'No playlists available yet.',
			'library_tap_to_play' => 'Tap to play',
			'library_uploaded_days_ago' => '{days} days ago',
			'library_uploaded_hour_ago' => '1 hour ago',
			'library_uploaded_hours_ago' => '{hours} hours ago',
			'library_uploaded_just_now' => 'Just now',
			'library_uploaded_minute_ago' => '1 minute ago',
			'library_uploaded_minutes_ago' => '{minutes} minutes ago',
			'library_uploaded_month_ago' => '1 month ago',
			'library_uploaded_months_ago' => '{months} months ago',
			'library_uploaded_week_ago' => '1 week ago',
			'library_uploaded_weeks_ago' => '{weeks} weeks ago',
			'library_uploaded_year_ago' => '1 year ago',
			'library_uploaded_years_ago' => '{years} years ago',
			'library_uploaded_yesterday' => 'Yesterday',
			'library_video_saved' => 'Video saved',
			'library_video_unsaved' => 'Video removed from saved',
			'library_view_all_playlists' => 'View all playlists',
			'library_whats_new' => 'Recent Uploads',
			'library_whats_new_empty' => 'No recent uploads yet.',
			'library_youtube_attribution' => 'Video hosted on YouTube',
			'library_youtube_not_configured' => 'Video library is not set up on the server yet. Radio Udaan staff need to add a YouTube API key in WordPress admin.',
			'link_open_failed' => 'Could not open link',
			'link_opens_in_browser' => 'Opens in browser',
			'link_unavailable' => 'This link is not available',
			'login_button' => 'Login',
			'login_email_intro' => 'Sign in with your verified email and password.',
			'login_email_verified_note' => 'Only verified email addresses can sign in here.',
			'login_mobile_hint' => 'Enter your details',
			'login_mobile_intro' => 'Sign in with your mobile number and password.',
			'login_mobile_label' => 'Mobile Number',
			'login_password_hint' => 'Enter your password',
			'login_welcome' => 'Welcome back. Let\'s get you listening.',
			'logout' => 'Logout',
			'logout_subtitle' => 'Securely sign out',
			'made_with_accessibility' => 'Made with accessibility in mind',
			'main_navigation' => 'Main navigation',
			'message_sent' => 'Message sent. Our team will reply soon.',
			'mobile_number_hint' => '+91 98765 43210',
			'mobile_number_label' => 'Mobile number',
			'more_options_intro' => '',
			'more_options_title' => 'More Options',
			'name_label' => 'Full Name',
			'name_required' => 'Enter your name.',
			'new_password' => 'New Password',
			'no_account_link' => 'Create an account',
			'not_signed_in' => 'Not signed in',
			'notification_read' => 'Read',
			'notification_unread' => 'Unread',
			'notification_open_hint' => 'Double tap to open',
			'notification_view_update' => 'View update',
			'notification_detail_title' => 'Notification',
			'notification_time_just_now' => 'Just now',
			'notification_time_minute_ago' => '1 minute ago',
			'notification_time_minutes_ago' => '{count} minutes ago',
			'notification_time_hour_ago' => '1 hour ago',
			'notification_time_hours_ago' => '{count} hours ago',
			'notification_time_yesterday' => 'Yesterday',
			'notification_time_days_ago' => '{count} days ago',
			'notifications_empty' => 'No notifications yet.',
			'notifications_filter_all' => 'All',
			'notifications_filter_unread' => 'Unread',
			'notifications_loading' => 'Loading notifications',
			'notifications_load_more' => 'Load more notifications',
			'notifications_loading_more' => 'Loading more notifications',
			'notifications_mark_all_read' => 'Mark all as read',
			'notifications_marked_all' => 'All notifications marked as read',
			'notifications_section' => 'Notifications',
			'notifications_subtitle' => 'Alerts and updates',
			'notifications_title' => 'Notifications',
			'notifications_unread_empty' => 'No unread notifications.',
			'notification_permission_title' => 'Stay connected to Radio Udaan',
			'notification_permission_body' => 'Allow notifications for live radio controls on your lock screen, plus alerts about events and station updates. You can change this anytime in Settings. Radio will still play if you choose Not now.',
			'notification_permission_continue' => 'Continue',
			'notification_permission_not_now' => 'Not now',
			'notify_event_alerts' => 'Event Alerts',
			'notify_live_broadcasts' => 'Live Broadcasts',
			'notify_promotions' => 'Promotions',
			'otp_code_incomplete' => 'Enter the full code from your SMS.',
			'otp_digit_hint' => 'Enter all digits from the SMS; up to 8 digits',
			'otp_enter_title' => 'Enter OTP',
			'otp_having_trouble' => 'Having trouble?',
			'otp_label' => 'Verification code',
			'otp_login_button' => 'LOGIN',
			'otp_pin_row_email_hint' => 'Enter {length} digits from your email',
			'otp_pin_row_empty' => 'Empty',
			'otp_pin_row_label' => 'Verification code',
			'otp_pin_row_sms_hint' => 'Enter {length} digits from your SMS',
			'otp_pin_row_value' => '{code} entered',
			'otp_resend_label' => 'Resend OTP',
			'otp_resent_success' => 'A new code has been sent. Check your SMS.',
			'otp_send_code' => 'Send code',
			'otp_sent_intro' => 'We have sent a 6-digit code to your mobile number',
			'otp_wait_prompt' => 'Didn\'t receive the code? Wait ',
			'otp_wait_timer' => '{minutes}:{seconds}',
			'password_changed_sign_in_again' => 'Password changed. Please sign in again.',
			'password_label' => 'Password',
			'password_min_hint' => 'Min. {min_length} characters',
			'password_mismatch' => 'Passwords do not match.',
			'password_required' => 'Enter your password.',
			'password_requirement_met' => '{requirement}, met',
			'password_requirement_not_met' => '{requirement}, not met',
			'password_requirements_not_met' => 'Please meet all password requirements.',
			'password_too_short' => 'Password is too short. Check the minimum length in settings.',
			'phone_country_search_hint' => 'Search country',
			'phone_field_helper' => 'Choose your country code, then enter your mobile number without the leading zero.',
			'phone_field_hint' => 'International mobile with country code, e.g. +91 98765 43210 or +1 555 123 4567',
			'phone_field_label' => 'Mobile number',
			'phone_invalid' => 'Enter a valid mobile number for the country you selected.',
			'phone_national_field_semantics' => 'Mobile number without country code',
			'phone_national_hint' => '98765 43210',
			'preferences_discarded' => 'Unsaved preference changes discarded',
			'preferences_save_failed' => 'Could not save preferences. Try again.',
			'preferences_saved' => 'Preferences saved',
			'privacy_policy' => 'Privacy policy',
			'profile' => 'Profile',
			'profile_email_locked_hint' => 'Linked to your account. Cannot be changed here.',
			'profile_email_semantics' => 'Email {email}. Cannot be changed.',
			'profile_email_verification_sent' => 'Verification code sent to your new email. Enter the code on the next screen.',
			'profile_info_note' => 'Your mobile number is fixed to your login. If you change your email, we send a verification code to the new address.',
			'profile_mobile_locked_hint' => 'Linked to your login. Cannot be changed here.',
			'profile_mobile_semantics' => 'Mobile number {phone}. Cannot be changed.',
			'profile_signed_in_semantics' => '{profile}, signed in as {parts}',
			'profile_updated' => 'Profile updated successfully',
			'radio_audio_unavailable' => 'Live radio could not start on this device. Check your internet connection and try Play again.',
			'radio_connecting' => 'Connecting…',
			'radio_favorite' => 'Favorite',
			'radio_favorite_add' => 'Add to favorites',
			'radio_favorite_announcement_added' => 'Added {show_title} to favorites',
			'radio_favorite_announcement_removed' => 'Removed {show_title} from favorites',
			'radio_favorite_button_add' => 'Add {show_title} to favorites',
			'radio_favorite_button_remove' => 'Remove {show_title} from favorites',
			'radio_favorite_remove' => 'Remove from favorites',
			'radio_intro' => 'Listen to Radio Udaan live.',
			'radio_live_label' => 'Live now',
			'radio_pause' => 'Pause',
			'radio_play' => 'Play Live Stream',
			'radio_play_on_air' => 'Play Live Stream. On air: {show}',
			'radio_playback_error' => 'Could not play live radio',
			'radio_playing' => 'Live radio is playing',
			'radio_schedule_empty' => 'No schedule available right now.',
			'radio_schedule_failed' => 'Could not load the schedule. Please try again.',
			'radio_schedule_station_time_label' => '{station_time} IST',
			'radio_schedule_dual_time_label' => '{station_time} IST · {local_time} your time',
			'radio_schedule_on_air' => 'On air now',
			'radio_schedule_repeat' => 'Repeat',
			'radio_schedule_title' => 'Radio schedule',
			'radio_share_live' => 'Share live',
			'radio_share_text_fallback' => 'Get the Radio Udaan app — community radio by and for persons with disabilities.',
			'radio_show_subtitle' => 'with RJ Karan & RJ Meera',
			'radio_show_title' => 'Udaan Morning Show',
			'radio_stop' => 'Stop Live Stream',
			'radio_stopped' => 'Live radio stopped',
			'radio_stream_missing' => 'Stream URL is not configured on the server.',
			'radio_upcoming_none' => 'No upcoming segments found.',
			'radio_upcoming_segments' => 'Upcoming segments',
			'radio_view_full_schedule' => 'View full schedule',
			'radio_volume' => 'Volume',
			'radio_volume_slider_hint' => 'Adjustable. Swipe up to increase or down to decrease volume in ten percent steps.',
			'radio_volume_announce' => 'Volume, {percent} percent',
			'radio_whatsapp_url_fallback' => '#',
			'radio_with_hosts_prefix' => 'with ',
			'reduce_motion' => 'Reduce Motion',
			'reduce_motion_hint' => 'Limit animations in the app',
			'register_a11y_body' => 'This form is optimized for screen readers and keyboard navigation. Large touch targets (64px+) and high contrast (4.5:1+) are enabled. Use Tab to move between fields.',
			'register_a11y_title' => 'Accessibility Assist',
			'register_button' => 'Register',
			'register_confirm_hint' => 'Repeat your password',
			'register_copyright' => '© 2024 Radio Udaan - Voice of Empowerment',
			'register_here' => 'Register Here',
			'register_intro' => 'Join our inclusive community and experience accessible radio like never before.',
			'register_mobile_hint' => '98765 43210',
			'register_name_hint' => 'Enter your full name',
			'register_password_hint' => 'Min. 8 characters',
			'register_title' => 'Create Account',
			'registration_account_locked_hint' => 'From your account, cannot edit.',
			'registration_address_hint' => 'Street, city, state, postal code',
			'registration_change_file_semantics' => 'Change file for {field_label}, {file_name}',
			'registration_choose_file_semantics' => 'Choose file for {field_label}',
			'registration_field_required' => 'This field is required.',
			'registration_incomplete' => 'Registration could not be completed.',
			'registration_multi_select_semantics_none' => 'None selected',
			'registration_multi_select_semantics_value' => 'Selected: {selected}',
			'registration_no_file_selected' => 'No file selected',
			'registration_picker_date_hint' => 'Double tap to choose date',
			'registration_picker_date_time_hint' => 'Double tap to choose date and time',
			'registration_picker_time_hint' => 'Double tap to choose time',
			'registration_success_prefix' => 'Registration submitted successfully. Reference: entry',
			'registration_success_title' => 'Registration submitted',
			'registration_success_body' => 'Thank you. We received your registration for {event_title}.',
			'registration_success_reference' => 'Reference number: {entry_id}',
			'registration_success_back' => 'Back to events',
			'registration_error_title' => 'Could not submit registration',
			'registration_unsupported_fields_semantics' => '{notice} Unsupported fields: {field_names}',
			'registration_upload_progress_label' => 'Uploading file for {field_label}, {percent} percent complete',
			'registration_upload_retry_label' => 'Retry upload for {field_label}',
			'resend_code' => 'Resend code',
			'resend_in_seconds' => 'Resend in {seconds}s',
			'resending_code_please_wait' => 'Sending a new code, please wait',
			'reset_email_code_required' => 'Enter the 6-digit code from your email.',
			'reset_password' => 'Reset password',
			'reset_password_button' => 'Reset Password',
			'reset_password_hero' => 'Reset password',
			'reset_password_intro' => 'Choose a new password.',
			'reset_password_sms_intro' => 'Choose a new password for {phone}.',
			'reset_password_success' => 'Password updated. You can sign in now.',
			'reset_password_title' => 'Reset password',
			'reset_token_label' => 'Reset link token',
			'reset_token_required' => 'Enter the reset link token from your email.',
			'retry' => 'Retry',
			'save_new_password' => 'Save New Password',
			'save_preferences' => 'Save Preferences',
			'schedule' => 'Schedule',
			'secure_verification_hero' => 'Secure verification',
			'semantics_loading' => 'Loading…',
			'send_code' => 'Send code',
			'send_message' => 'Send Message',
			'send_reset_link' => 'Send reset instructions',
			'send_us_a_message' => 'Send us a message',
			'sending_code_please_wait' => 'Sending code, please wait',
			'settings_intro' => 'Customize your accessibility and notification preferences.',
			'settings_subtitle' => 'Accessibility and notifications',
			'settings_title' => 'Settings',
			'share' => 'Share',
			'share_copied' => 'Share message copied to clipboard',
			'share_failed' => 'Could not open share sheet',
			'share_unavailable' => 'Sharing is not available on this device',
			'show_password' => 'Show password',
			'sign_in' => 'Sign in',
			'sign_in_here' => 'Sign In here',
			'sign_in_intro' => 'Choose your country code and mobile number. We will send a one-time code by SMS.',
			'sign_in_password_intro' => 'Sign in with your email or mobile number and password.',
			'sign_in_title' => 'Sign in',
			'sign_in_with_email' => 'Login using email',
			'sign_in_with_mobile' => 'Login using mobile',
			'sign_in_with_otp' => 'Login with OTP',
			'sign_in_with_password' => 'Sign in with password',
			'sign_out' => 'Sign out',
			'signing_out' => 'Signing out',
			'splash_a11y_badge' => 'Optimized for screen readers',
			'splash_tagline' => '...A flight of life',
			'still_need_help' => 'Still need help?',
			'submit_registration' => 'Submit Registration',
			'submitting_registration_please_wait' => 'Submitting registration, please wait',
			'tab_about' => 'About',
			'tab_events' => 'Events',
			'tab_library' => 'Library',
			'tab_more' => 'More',
			'tab_radio' => 'Live Radio',
			'tap_to_update_photo' => 'Tap to update photo',
			'terms_of_use' => 'Terms of use',
			'text_size' => 'Text Size',
			'text_size_faster' => 'Larger',
			'text_size_normal' => 'Normal',
			'text_size_slider_hint' => 'Drag to adjust text size from smaller to larger',
			'text_size_slower' => 'Smaller',
			'unknown' => 'Unknown',
			'unread_notifications_badge_many' => '{count} unread notifications',
			'unread_notifications_badge_one' => '1 unread notification',
			'unsupported_fields_notice' => 'Some fields on this form are not supported in the app yet. Contact Radio Udaan if you need help completing them.',
			'update_profile' => 'Update Profile',
			'user_profile' => 'User Profile',
			'user_profile_subtitle' => 'Update your information',
			'verification_code_hint' => 'Enter the 6-digit code from your email.',
			'verification_code_label' => 'Verification code',
			'verification_code_required' => 'Enter the 6-digit verification code.',
			'verification_code_resent' => 'A new verification code has been sent.',
			'verification_incomplete' => 'Verification did not complete. Try again.',
			'verify_and_continue' => 'Verify and continue',
			'verify_button' => 'Verify',
			'phone_country_code_semantics' => 'Country code, {country_name}, plus {dial_code}. Double tap to change country.',
			'verify_email_intro' => 'Enter the 6-digit code we sent to your email.',
			'verify_email_link' => 'Verify email',
			'verify_email_sent_to' => 'We sent a 6-digit code to {email}.',
			'verify_email_title' => 'Verify email',
			'whats_new_detail_loading' => 'Loading update',
			'whats_new_empty' => 'No updates yet.',
			'whats_new_kind_announcement' => 'Announcement',
			'whats_new_kind_community_news' => 'Community News',
			'whats_new_kind_in_news' => 'In the News',
			'whats_new_read_article' => 'Read article',
			'whats_new_read_article_hint' => 'Opens the news article in your browser',
			'whats_new_watch_youtube' => 'Watch on YouTube',
			'verify_identity_hero' => 'Verify your identity',
			'verify_identity_intro' => 'We\'ve sent a 6-digit security code to your registered mobile number ending in',
			'verify_identity_title' => 'Verify Identity',
			'verify_intro' => 'Enter the code sent to your number. Type the digits manually — the app does not read SMS.',
			'verify_intro_manual' => 'Enter the code sent to your number. Type the digits manually — the app does not read SMS.',
			'verify_title' => 'Verify code',
			'verifying_code_please_wait' => 'Verifying code, please wait',
		);
	}

	/**
	 * Admin UI groups: title => list of catalog keys.
	 *
	 * @return array<string,array<int,string>>
	 */
	public static function groups() {
		return array(
			'General' => array(
				'app_name',
				'back_button',
				'back_to_login',
				'bootstrap_loading',
				'bootstrap_offline',
				'force_update_title',
				'force_update_message',
				'force_update_current_build',
				'force_update_button',
				'cancel',
				'join_whats_app_channel',
				'link_open_failed',
				'link_opens_in_browser',
				'link_unavailable',
				'main_navigation',
				'no_account_link',
				'retry',
				'semantics_loading',
				'share',
				'share_copied',
				'share_failed',
				'share_unavailable',
				'splash_a11y_badge',
				'splash_tagline',
				'submitting_registration_please_wait',
				'tab_about',
				'tab_events',
				'tab_library',
				'tab_more',
				'tab_radio',
				'unknown',
			),
			'Auth' => array(
				'account_icon',
				'app_logo_semantics',
				'branding_logo_semantics',
				'confirm_password_label',
				'create_account',
				'dont_have_account',
				'email_hint',
				'email_label',
				'email_not_verified',
				'forgot_password_channel_email',
				'forgot_password_channel_phone',
				'forgot_password_channel_semantics',
				'forgot_password_email_hint',
				'forgot_password_email_note',
				'forgot_password_intro',
				'forgot_password_link',
				'forgot_password_phone_note',
				'forgot_password_success',
				'forgot_password_title',
				'has_account_link',
				'has_account_prompt',
				'hide_password',
				'identifier_hint',
				'identifier_label',
				'login_button',
				'login_email_intro',
				'login_email_verified_note',
				'login_mobile_hint',
				'login_mobile_intro',
				'login_mobile_label',
				'login_password_hint',
				'login_welcome',
				'mobile_number_hint',
				'mobile_number_label',
				'name_label',
				'otp_digit_hint',
				'otp_enter_title',
				'otp_having_trouble',
				'otp_label',
				'otp_login_button',
				'otp_pin_row_email_hint',
				'otp_pin_row_empty',
				'otp_pin_row_label',
				'otp_pin_row_sms_hint',
				'otp_pin_row_value',
				'otp_resend_label',
				'otp_resent_success',
				'otp_send_code',
				'otp_sent_intro',
				'otp_wait_prompt',
				'otp_wait_timer',
				'password_label',
				'password_min_hint',
				'password_requirement_met',
				'phone_country_search_hint',
				'phone_field_helper',
				'phone_field_hint',
				'phone_field_label',
				'phone_national_field_semantics',
				'phone_national_hint',
				'register_a11y_body',
				'register_a11y_title',
				'register_button',
				'register_confirm_hint',
				'register_copyright',
				'register_here',
				'register_intro',
				'register_mobile_hint',
				'register_name_hint',
				'register_password_hint',
				'register_title',
				'resend_code',
				'resend_in_seconds',
				'resending_code_please_wait',
				'reset_password',
				'reset_password_button',
				'reset_password_hero',
				'reset_password_intro',
				'reset_password_sms_intro',
				'reset_password_success',
				'reset_password_title',
				'reset_token_label',
				'secure_verification_hero',
				'send_code',
				'send_reset_link',
				'sending_code_please_wait',
				'show_password',
				'sign_in',
				'sign_in_here',
				'sign_in_intro',
				'sign_in_password_intro',
				'sign_in_title',
				'sign_in_with_email',
				'sign_in_with_mobile',
				'sign_in_with_otp',
				'sign_in_with_password',
				'verification_code_hint',
				'verification_code_label',
				'verification_code_resent',
				'verify_and_continue',
				'verify_button',
				'phone_country_code_semantics',
				'verify_email_intro',
				'verify_email_link',
				'verify_email_sent_to',
				'verify_email_title',
				'verify_identity_hero',
				'verify_identity_intro',
				'verify_identity_title',
				'verify_intro',
				'verify_intro_manual',
				'verify_title',
				'verifying_code_please_wait',
			),
			'Radio' => array(
				'join_the_discussion',
				'radio_audio_unavailable',
				'radio_connecting',
				'radio_favorite',
				'radio_favorite_add',
				'radio_favorite_announcement_added',
				'radio_favorite_announcement_removed',
				'radio_favorite_button_add',
				'radio_favorite_button_remove',
				'radio_favorite_remove',
				'radio_intro',
				'radio_live_label',
				'radio_pause',
				'radio_play',
				'radio_play_on_air',
				'radio_playback_error',
				'radio_playing',
				'radio_schedule_empty',
				'radio_schedule_failed',
				'radio_schedule_station_time_label',
				'radio_schedule_dual_time_label',
				'radio_schedule_on_air',
				'radio_schedule_repeat',
				'radio_schedule_title',
				'radio_share_live',
				'radio_share_text_fallback',
				'radio_show_subtitle',
				'radio_show_title',
				'radio_stop',
				'radio_stopped',
				'radio_stream_missing',
				'radio_upcoming_none',
				'radio_upcoming_segments',
				'radio_view_full_schedule',
				'radio_volume',
				'radio_volume_slider_hint',
				'radio_volume_announce',
				'radio_whatsapp_url_fallback',
				'radio_with_hosts_prefix',
				'schedule',
			),
			'Events' => array(
				'choose_file',
				'event_deep_link_loading',
				'event_deep_link_opening',
				'event_registration_loading_form',
				'event_registration_retry_load',
				'event_registration_title',
				'events_empty',
				'events_loading',
				'events_page_intro',
				'events_page_title',
				'events_register_now',
				'events_registration_closed',
				'registration_account_locked_hint',
				'registration_address_hint',
				'registration_change_file_semantics',
				'registration_choose_file_semantics',
				'registration_field_required',
				'registration_incomplete',
				'registration_multi_select_semantics_none',
				'registration_multi_select_semantics_value',
				'registration_no_file_selected',
				'registration_picker_date_hint',
				'registration_picker_date_time_hint',
				'registration_picker_time_hint',
				'registration_success_prefix',
				'registration_success_title',
				'registration_success_body',
				'registration_success_reference',
				'registration_success_back',
				'registration_error_title',
				'registration_unsupported_fields_semantics',
				'registration_upload_progress_label',
				'registration_upload_retry_label',
				'submit_registration',
				'unsupported_fields_notice',
			),
			'Library' => array(
				'library_duration_prefix',
				'library_embed_error',
				'library_loading',
				'library_no_description',
				'library_no_video',
				'library_open_in_youtube',
				'library_play_video',
				'library_player_buffering',
				'library_player_paused',
				'library_playlist_videos_empty',
				'library_playlists',
				'library_playlists_empty',
				'library_saved_screen_title',
				'library_saved_entry_subtitle',
				'library_saved_radio_section',
				'library_saved_videos_section',
				'library_saved_empty',
				'library_recent_uploads',
				'library_recent_uploads_empty',
				'library_save_video',
				'library_saved_video',
				'library_search_clear',
				'library_search_cleared',
				'library_search_empty',
				'library_search_hint',
				'library_search_videos',
				'library_shows',
				'library_shows_empty',
				'library_tap_to_play',
				'library_uploaded_days_ago',
				'library_uploaded_hour_ago',
				'library_uploaded_hours_ago',
				'library_uploaded_just_now',
				'library_uploaded_minute_ago',
				'library_uploaded_minutes_ago',
				'library_uploaded_month_ago',
				'library_uploaded_months_ago',
				'library_uploaded_week_ago',
				'library_uploaded_weeks_ago',
				'library_uploaded_year_ago',
				'library_uploaded_years_ago',
				'library_uploaded_yesterday',
				'library_video_saved',
				'library_video_unsaved',
				'library_view_all_playlists',
				'library_whats_new',
				'library_whats_new_empty',
				'library_youtube_attribution',
				'library_youtube_not_configured',
			),
			'About' => array(
				'about_options_intro',
				'about_options_title',
				'about_us',
				'about_us_subtitle',
				'about_whats_new',
				'about_whats_new_subtitle',
				'whats_new_detail_loading',
				'whats_new_empty',
				'whats_new_kind_announcement',
				'whats_new_kind_community_news',
				'whats_new_kind_in_news',
				'whats_new_read_article',
				'whats_new_read_article_hint',
				'whats_new_watch_youtube',
				'contact_email_subtitle',
				'contact_email_title',
				'contact_number_subtitle',
				'contact_number_title',
				'copied_to_clipboard',
				'copy_value',
				'donate_bank_details_title',
				'donate_scan_caption',
				'donate_scan_title',
				'donate_us',
				'donate_us_subtitle',
				'donate_pay_online_title',
				'donate_pay_online_subtitle',
				'donate_pay_online_subtitle_ios',
				'donate_amount_heading',
				'donate_amount_chip_semantics',
				'donate_selected_summary',
				'donate_amount_custom_label',
				'donate_amount_custom_hint',
				'donate_now_button',
				'donate_now_with_amount',
				'donate_now_loading',
				'donate_success_title',
				'donate_success_message',
				'donate_failed_message',
				'donate_80g_checkbox',
				'donate_80g_hint',
				'donate_pan_label',
				'donate_pan_required',
				'donate_form_10be_note',
				'donate_email_from_account',
				'donate_custom_amount_selected',
				'donate_opening_payment',
				'donate_opening_with_amount',
				'donate_check_payment',
				'donate_ios_waiting',
				'donate_ios_confirming',
				'donate_verifying',
				'donate_back_to_donate',
				'donate_invalid_amount',
				'follow_us',
				'label_account_name',
				'label_account_number',
				'label_bank_address',
				'label_bank_name',
				'label_branch_name',
				'label_ifsc',
				'label_micr',
				'label_upi_id',
				'tab_about',
			),
			'More' => array(
				'about_us',
				'about_us_subtitle',
				'account_deleted_signing_out',
				'app_version_label',
				'change_password_intro',
				'change_password_title',
				'confirm_new_password',
				'current_password',
				'delete_account',
				'delete_account_confirm_body',
				'delete_account_confirm_title',
				'delete_account_subtitle',
				'edit_profile_title',
				'legal_section',
				'logout',
				'logout_subtitle',
				'made_with_accessibility',
				'more_options_intro',
				'more_options_title',
				'new_password',
				'not_signed_in',
				'password_changed_sign_in_again',
				'password_requirements_not_met',
				'privacy_policy',
				'profile',
				'profile_email_locked_hint',
				'profile_email_semantics',
				'profile_email_verification_sent',
				'profile_info_note',
				'profile_mobile_locked_hint',
				'profile_mobile_semantics',
				'profile_signed_in_semantics',
				'profile_updated',
				'save_new_password',
				'sign_out',
				'signing_out',
				'tap_to_update_photo',
				'terms_of_use',
				'update_profile',
				'user_profile',
				'user_profile_subtitle',
			),
			'Settings' => array(
				'accessibility_section',
				'bold_text',
				'bold_text_hint',
				'high_contrast_mode',
				'high_contrast_mode_hint',
				'preferences_discarded',
				'preferences_save_failed',
				'preferences_saved',
				'reduce_motion',
				'reduce_motion_hint',
				'save_preferences',
				'settings_intro',
				'settings_subtitle',
				'settings_title',
				'text_size',
				'text_size_faster',
				'text_size_normal',
				'text_size_slider_hint',
				'text_size_slower',
			),
			'Help' => array(
				'call_accessibility_helpline',
				'contact_form_intro',
				'contact_form_title',
				'contact_support',
				'contact_title',
				'email_support',
				'forgot_password_help_body',
				'help_and_contact',
				'help_and_contact_subtitle',
				'help_faq_topics',
				'help_message',
				'help_search_hint',
				'help_subject',
				'help_title',
				'join_community',
				'message_sent',
				'send_message',
				'send_us_a_message',
				'still_need_help',
			),
			'Notifications' => array(
				'notification_read',
				'notification_unread',
				'notification_open_hint',
				'notification_view_update',
				'notification_detail_title',
				'notification_time_just_now',
				'notification_time_minute_ago',
				'notification_time_minutes_ago',
				'notification_time_hour_ago',
				'notification_time_hours_ago',
				'notification_time_yesterday',
				'notification_time_days_ago',
				'notifications_empty',
				'notifications_filter_all',
				'notifications_filter_unread',
				'notifications_loading',
				'notifications_load_more',
				'notifications_loading_more',
				'notifications_mark_all_read',
				'notifications_marked_all',
				'notifications_section',
				'notifications_subtitle',
				'notifications_title',
				'notifications_unread_empty',
				'notification_permission_title',
				'notification_permission_body',
				'notification_permission_continue',
				'notification_permission_not_now',
				'notify_event_alerts',
				'notify_live_broadcasts',
				'notify_promotions',
				'unread_notifications_badge_many',
				'unread_notifications_badge_one',
			),
			'Errors/validation' => array(
				'account_delete_failed',
				'email_invalid',
				'identifier_invalid',
				'name_required',
				'otp_code_incomplete',
				'password_mismatch',
				'password_required',
				'password_requirement_not_met',
				'password_too_short',
				'phone_invalid',
				'reset_email_code_required',
				'reset_token_required',
				'verification_code_required',
				'verification_incomplete',
			),
		);
	}

	/**
	 * Human-readable label for a catalog key.
	 *
	 * @param string $key Catalog key.
	 * @return string
	 */
	public static function field_label( $key ) {
		$labels = array(
			'about_us' => 'About Us',
			'about_us_subtitle' => 'About Us Subtitle',
			'about_whats_new' => "About What's New",
			'about_whats_new_subtitle' => "About What's New Subtitle",
			'accessibility_section' => 'Accessibility Section',
			'account_delete_failed' => 'Account Delete Failed',
			'account_deleted_signing_out' => 'Account Deleted Signing Out',
			'account_icon' => 'Account Icon',
			'app_logo_semantics' => 'App Logo Semantics',
			'app_name' => 'App Name',
			'app_version_label' => 'App Version Label',
			'back_button' => 'Back Button',
			'back_to_login' => 'Back To Login',
			'bold_text' => 'Bold Text',
			'bold_text_hint' => 'Bold Text Hint',
			'bootstrap_loading' => 'Bootstrap Loading',
			'bootstrap_offline' => 'Bootstrap Offline',
			'force_update_title' => 'Force Update Title',
			'force_update_message' => 'Force Update Message',
			'force_update_current_build' => 'Force Update Current Build',
			'force_update_button' => 'Force Update Button',
			'branding_logo_semantics' => 'Branding Logo Semantics',
			'call_accessibility_helpline' => 'Call Accessibility Helpline',
			'cancel' => 'Cancel',
			'change_password_intro' => 'Change Password Intro',
			'change_password_title' => 'Change Password Title',
			'choose_file' => 'Choose File',
			'confirm_new_password' => 'Confirm New Password',
			'confirm_password_label' => 'Confirm Password Label',
			'contact_form_intro' => 'Contact Form Intro',
			'contact_form_title' => 'Contact Form Title',
			'contact_support' => 'Contact Support',
			'contact_title' => 'Contact Title',
			'create_account' => 'Create Account',
			'current_password' => 'Current Password',
			'delete_account' => 'Delete Account',
			'delete_account_confirm_body' => 'Delete Account Confirm Body',
			'delete_account_confirm_title' => 'Delete Account Confirm Title',
			'delete_account_subtitle' => 'Delete Account Subtitle',
			'dont_have_account' => 'Dont Have Account',
			'donate_80g_checkbox' => 'Donate 80G Checkbox',
			'donate_80g_hint' => 'Donate 80G Hint',
			'donate_amount_chip_semantics' => 'Donate Amount Chip Semantics',
			'donate_amount_custom_hint' => 'Donate Amount Custom Hint',
			'donate_amount_custom_label' => 'Donate Amount Custom Label',
			'donate_amount_heading' => 'Donate Amount Heading',
			'donate_back_to_donate' => 'Donate Back To Donate',
			'donate_bank_details_title' => 'Donate Bank Details Title',
			'donate_check_payment' => 'Donate Check Payment',
			'donate_custom_amount_selected' => 'Donate Custom Amount Selected',
			'donate_email_from_account' => 'Donate Email From Account',
			'donate_failed_message' => 'Donate Failed Message',
			'donate_form_10be_note' => 'Donate Form 10BE Note',
			'donate_invalid_amount' => 'Donate Invalid Amount',
			'donate_ios_confirming' => 'Donate iOS Confirming',
			'donate_ios_waiting' => 'Donate iOS Waiting',
			'donate_now_button' => 'Donate Now Button',
			'donate_now_loading' => 'Donate Now Loading',
			'donate_now_with_amount' => 'Donate Now With Amount',
			'donate_opening_payment' => 'Donate Opening Payment',
			'donate_opening_with_amount' => 'Donate Opening With Amount',
			'donate_pan_label' => 'Donate PAN Label',
			'donate_pan_required' => 'Donate PAN Required',
			'donate_pay_online_subtitle' => 'Donate Pay Online Subtitle',
			'donate_pay_online_subtitle_ios' => 'Donate Pay Online Subtitle iOS',
			'donate_pay_online_title' => 'Donate Pay Online Title',
			'donate_scan_caption' => 'Donate Scan Caption',
			'donate_scan_title' => 'Donate Scan Title',
			'donate_selected_summary' => 'Donate Selected Summary',
			'donate_success_message' => 'Donate Success Message',
			'donate_success_title' => 'Donate Success Title',
			'donate_us' => 'Donate Us',
			'donate_us_subtitle' => 'Donate Us Subtitle',
			'donate_verifying' => 'Donate Verifying',
			'edit_profile_title' => 'Edit Profile Title',
			'email_hint' => 'Email Hint',
			'email_invalid' => 'Email Invalid',
			'email_label' => 'Email Label',
			'email_not_verified' => 'Email Not Verified',
			'email_support' => 'Email Support',
			'event_deep_link_loading' => 'Event Deep Link Loading',
			'event_deep_link_opening' => 'Event Deep Link Opening',
			'event_registration_loading_form' => 'Event Registration Loading Form',
			'event_registration_retry_load' => 'Event Registration Retry Load',
			'event_registration_title' => 'Event Registration Title',
			'events_empty' => 'Events Empty',
			'events_loading' => 'Events Loading',
			'events_page_intro' => 'Events Page Intro',
			'events_page_title' => 'Events Page Title',
			'events_register_now' => 'Events Register Now',
			'events_registration_closed' => 'Events Registration Closed',
			'forgot_password_channel_email' => 'Forgot Password Channel Email',
			'forgot_password_channel_phone' => 'Forgot Password Channel Phone',
			'forgot_password_channel_semantics' => 'Forgot Password Channel Semantics',
			'forgot_password_email_hint' => 'Forgot Password Email Hint',
			'forgot_password_email_note' => 'Forgot Password Email Note',
			'forgot_password_help_body' => 'Forgot Password Help Body',
			'forgot_password_intro' => 'Forgot Password Intro',
			'forgot_password_link' => 'Forgot Password Link',
			'forgot_password_phone_note' => 'Forgot Password Phone Note',
			'forgot_password_success' => 'Forgot Password Success',
			'forgot_password_title' => 'Forgot Password Title',
			'has_account_link' => 'Has Account Link',
			'has_account_prompt' => 'Has Account Prompt',
			'help_and_contact' => 'Help And Contact',
			'help_and_contact_subtitle' => 'Help And Contact Subtitle',
			'help_faq_topics' => 'Help Faq Topics',
			'help_message' => 'Help Message',
			'help_search_hint' => 'Help Search Hint',
			'help_subject' => 'Help Subject',
			'help_title' => 'Help Title',
			'hide_password' => 'Hide Password',
			'high_contrast_mode' => 'High Contrast Mode',
			'high_contrast_mode_hint' => 'High Contrast Mode Hint',
			'identifier_hint' => 'Identifier Hint',
			'identifier_invalid' => 'Identifier Invalid',
			'identifier_label' => 'Identifier Label',
			'join_community' => 'Join Community',
			'join_the_discussion' => 'Join The Discussion',
			'join_whats_app_channel' => 'Join Whats App Channel',
			'legal_section' => 'Legal Section',
			'library_duration_prefix' => 'Library Duration Prefix',
			'library_embed_error' => 'Library Embed Error',
			'library_loading' => 'Library Loading',
			'library_no_description' => 'Library No Description',
			'library_no_video' => 'Library No Video',
			'library_open_in_youtube' => 'Library Open In Youtube',
			'library_play_video' => 'Library Play Video',
			'library_player_buffering' => 'Library Player Buffering',
			'library_player_paused' => 'Library Player Paused',
			'library_playlist_videos_empty' => 'Library Playlist Videos Empty',
			'library_playlists' => 'Library Playlists',
			'library_playlists_empty' => 'Library Playlists Empty',
			'library_saved_screen_title' => 'Library Saved Screen Title',
			'library_saved_entry_subtitle' => 'Library Saved Entry Subtitle',
			'library_saved_radio_section' => 'Library Saved Radio Section',
			'library_saved_videos_section' => 'Library Saved Videos Section',
			'library_saved_empty' => 'Library Saved Empty',
			'library_recent_uploads' => 'Library Recent Uploads',
			'library_recent_uploads_empty' => 'Library Recent Uploads Empty',
			'library_save_video' => 'Library Save Video',
			'library_saved_video' => 'Library Saved Video',
			'library_search_clear' => 'Library Search Clear',
			'library_search_cleared' => 'Library Search Cleared',
			'library_search_empty' => 'Library Search Empty',
			'library_search_hint' => 'Library Search Hint',
			'library_search_videos' => 'Library Search Videos',
			'library_shows' => 'Library Shows',
			'library_shows_empty' => 'Library Shows Empty',
			'library_tap_to_play' => 'Library Tap To Play',
			'library_uploaded_days_ago' => 'Library Uploaded Days Ago',
			'library_uploaded_hour_ago' => 'Library Uploaded Hour Ago',
			'library_uploaded_hours_ago' => 'Library Uploaded Hours Ago',
			'library_uploaded_just_now' => 'Library Uploaded Just Now',
			'library_uploaded_minute_ago' => 'Library Uploaded Minute Ago',
			'library_uploaded_minutes_ago' => 'Library Uploaded Minutes Ago',
			'library_uploaded_month_ago' => 'Library Uploaded Month Ago',
			'library_uploaded_months_ago' => 'Library Uploaded Months Ago',
			'library_uploaded_week_ago' => 'Library Uploaded Week Ago',
			'library_uploaded_weeks_ago' => 'Library Uploaded Weeks Ago',
			'library_uploaded_year_ago' => 'Library Uploaded Year Ago',
			'library_uploaded_years_ago' => 'Library Uploaded Years Ago',
			'library_uploaded_yesterday' => 'Library Uploaded Yesterday',
			'library_video_saved' => 'Library Video Saved',
			'library_video_unsaved' => 'Library Video Unsaved',
			'library_view_all_playlists' => 'Library View All Playlists',
			'library_whats_new' => 'Library Whats New',
			'library_whats_new_empty' => 'Library Whats New Empty',
			'library_youtube_attribution' => 'Library Youtube Attribution',
			'library_youtube_not_configured' => 'Library Youtube Not Configured',
			'link_open_failed' => 'Link Open Failed',
			'link_opens_in_browser' => 'Link Opens In Browser',
			'link_unavailable' => 'Link Unavailable',
			'login_button' => 'Login Button',
			'login_email_intro' => 'Login Email Intro',
			'login_email_verified_note' => 'Login Email Verified Note',
			'login_mobile_hint' => 'Login Mobile Hint',
			'login_mobile_intro' => 'Login Mobile Intro',
			'login_mobile_label' => 'Login Mobile Label',
			'login_password_hint' => 'Login Password Hint',
			'login_welcome' => 'Login Welcome',
			'logout' => 'Logout',
			'logout_subtitle' => 'Logout Subtitle',
			'made_with_accessibility' => 'Made With Accessibility',
			'main_navigation' => 'Main Navigation',
			'message_sent' => 'Message Sent',
			'mobile_number_hint' => 'Mobile Number Hint',
			'mobile_number_label' => 'Mobile Number Label',
			'more_options_intro' => 'More Options Intro',
			'more_options_title' => 'More Options Title',
			'name_label' => 'Name Label',
			'name_required' => 'Name Required',
			'new_password' => 'New Password',
			'no_account_link' => 'No Account Link',
			'not_signed_in' => 'Not Signed In',
			'notification_open_hint' => 'Notification Open Hint',
			'notification_read' => 'Notification Read',
			'notification_unread' => 'Notification Unread',
			'notification_view_update' => 'Notification View Update',
			'notification_detail_title' => 'Notification Detail Title',
			'notification_time_just_now' => 'Notification Time Just Now',
			'notification_time_minute_ago' => 'Notification Time Minute Ago',
			'notification_time_minutes_ago' => 'Notification Time Minutes Ago',
			'notification_time_hour_ago' => 'Notification Time Hour Ago',
			'notification_time_hours_ago' => 'Notification Time Hours Ago',
			'notification_time_yesterday' => 'Notification Time Yesterday',
			'notification_time_days_ago' => 'Notification Time Days Ago',
			'notifications_empty' => 'Notifications Empty',
			'notifications_filter_all' => 'Notifications Filter All',
			'notifications_filter_unread' => 'Notifications Filter Unread',
			'notifications_loading' => 'Notifications Loading',
			'notifications_load_more' => 'Notifications Load More',
			'notifications_loading_more' => 'Notifications Loading More',
			'notifications_mark_all_read' => 'Notifications Mark All Read',
			'notifications_marked_all' => 'Notifications Marked All',
			'notifications_section' => 'Notifications Section',
			'notifications_subtitle' => 'Notifications Subtitle',
			'notifications_title' => 'Notifications Title',
			'notifications_unread_empty' => 'Notifications Unread Empty',
			'notification_permission_title' => 'Notification Permission Title',
			'notification_permission_body' => 'Notification Permission Body',
			'notification_permission_continue' => 'Notification Permission Continue',
			'notification_permission_not_now' => 'Notification Permission Not Now',
			'notify_event_alerts' => 'Notify Event Alerts',
			'notify_live_broadcasts' => 'Notify Live Broadcasts',
			'notify_promotions' => 'Notify Promotions',
			'otp_code_incomplete' => 'Otp Code Incomplete',
			'otp_digit_hint' => 'Otp Digit Hint',
			'otp_enter_title' => 'Otp Enter Title',
			'otp_having_trouble' => 'Otp Having Trouble',
			'otp_label' => 'Otp Label',
			'otp_login_button' => 'Otp Login Button',
			'otp_pin_row_email_hint' => 'Otp Pin Row Email Hint',
			'otp_pin_row_empty' => 'Otp Pin Row Empty',
			'otp_pin_row_label' => 'Otp Pin Row Label',
			'otp_pin_row_sms_hint' => 'Otp Pin Row Sms Hint',
			'otp_pin_row_value' => 'Otp Pin Row Value',
			'otp_resend_label' => 'Otp Resend Label',
			'otp_resent_success' => 'Otp Resent Success',
			'otp_send_code' => 'Otp Send Code',
			'otp_sent_intro' => 'Otp Sent Intro',
			'otp_wait_prompt' => 'Otp Wait Prompt',
			'otp_wait_timer' => 'Otp Wait Timer',
			'password_changed_sign_in_again' => 'Password Changed Sign In Again',
			'password_label' => 'Password Label',
			'password_min_hint' => 'Password Min Hint',
			'password_mismatch' => 'Password Mismatch',
			'password_required' => 'Password Required',
			'password_requirement_met' => 'Password Requirement Met',
			'password_requirement_not_met' => 'Password Requirement Not Met',
			'password_requirements_not_met' => 'Password Requirements Not Met',
			'password_too_short' => 'Password Too Short',
			'phone_country_search_hint' => 'Phone Country Search Hint',
			'phone_field_helper' => 'Phone Field Helper',
			'phone_field_hint' => 'Phone Field Hint',
			'phone_field_label' => 'Phone Field Label',
			'phone_invalid' => 'Phone Invalid',
			'phone_national_field_semantics' => 'Phone National Field Semantics',
			'phone_national_hint' => 'Phone National Hint',
			'preferences_discarded' => 'Preferences Discarded',
			'preferences_save_failed' => 'Preferences Save Failed',
			'preferences_saved' => 'Preferences Saved',
			'privacy_policy' => 'Privacy Policy',
			'profile' => 'Profile',
			'profile_email_locked_hint' => 'Profile Email Locked Hint',
			'profile_email_semantics' => 'Profile Email Semantics',
			'profile_email_verification_sent' => 'Profile Email Verification Sent',
			'profile_info_note' => 'Profile Info Note',
			'profile_mobile_locked_hint' => 'Profile Mobile Locked Hint',
			'profile_mobile_semantics' => 'Profile Mobile Semantics',
			'profile_signed_in_semantics' => 'Profile Signed In Semantics',
			'profile_updated' => 'Profile Updated',
			'radio_audio_unavailable' => 'Radio Audio Unavailable',
			'radio_connecting' => 'Radio Connecting',
			'radio_favorite' => 'Radio Favorite',
			'radio_favorite_add' => 'Radio Favorite Add',
			'radio_favorite_announcement_added' => 'Radio Favorite Announcement Added',
			'radio_favorite_announcement_removed' => 'Radio Favorite Announcement Removed',
			'radio_favorite_button_add' => 'Radio Favorite Button Add',
			'radio_favorite_button_remove' => 'Radio Favorite Button Remove',
			'radio_favorite_remove' => 'Radio Favorite Remove',
			'radio_intro' => 'Radio Intro',
			'radio_live_label' => 'Radio Live Label',
			'radio_pause' => 'Radio Pause',
			'radio_play' => 'Radio Play',
			'radio_play_on_air' => 'Radio Play On Air',
			'radio_playback_error' => 'Radio Playback Error',
			'radio_playing' => 'Radio Playing',
			'radio_schedule_empty' => 'Radio Schedule Empty',
			'radio_schedule_failed' => 'Radio Schedule Failed',
			'radio_schedule_station_time_label' => 'Radio Schedule Station Time Label',
			'radio_schedule_dual_time_label' => 'Radio Schedule Dual Time Label',
			'radio_schedule_on_air' => 'Radio Schedule On Air',
			'radio_schedule_repeat' => 'Radio Schedule Repeat',
			'radio_schedule_title' => 'Radio Schedule Title',
			'radio_share_live' => 'Radio Share Live',
			'radio_share_text_fallback' => 'Radio Share Text Fallback',
			'radio_show_subtitle' => 'Radio Show Subtitle',
			'radio_show_title' => 'Radio Show Title',
			'radio_stop' => 'Radio Stop',
			'radio_stopped' => 'Radio Stopped',
			'radio_stream_missing' => 'Radio Stream Missing',
			'radio_upcoming_none' => 'Radio Upcoming None',
			'radio_upcoming_segments' => 'Radio Upcoming Segments',
			'radio_view_full_schedule' => 'Radio View Full Schedule',
			'radio_volume' => 'Radio Volume',
			'radio_volume_slider_hint' => 'Radio Volume Slider Hint',
			'radio_volume_announce' => 'Radio Volume Announce',
			'radio_whatsapp_url_fallback' => 'Radio Whatsapp Url Fallback',
			'radio_with_hosts_prefix' => 'Radio With Hosts Prefix',
			'reduce_motion' => 'Reduce Motion',
			'reduce_motion_hint' => 'Reduce Motion Hint',
			'register_a11y_body' => 'Register A11Y Body',
			'register_a11y_title' => 'Register A11Y Title',
			'register_button' => 'Register Button',
			'register_confirm_hint' => 'Register Confirm Hint',
			'register_copyright' => 'Register Copyright',
			'register_here' => 'Register Here',
			'register_intro' => 'Register Intro',
			'register_mobile_hint' => 'Register Mobile Hint',
			'register_name_hint' => 'Register Name Hint',
			'register_password_hint' => 'Register Password Hint',
			'register_title' => 'Register Title',
			'registration_account_locked_hint' => 'Registration Account Locked Hint',
			'registration_address_hint' => 'Registration Address Hint',
			'registration_change_file_semantics' => 'Registration Change File Semantics',
			'registration_choose_file_semantics' => 'Registration Choose File Semantics',
			'registration_field_required' => 'Registration Field Required',
			'registration_incomplete' => 'Registration Incomplete',
			'registration_multi_select_semantics_none' => 'Registration Multi Select Semantics None',
			'registration_multi_select_semantics_value' => 'Registration Multi Select Semantics Value',
			'registration_no_file_selected' => 'Registration No File Selected',
			'registration_picker_date_hint' => 'Registration Picker Date Hint',
			'registration_picker_date_time_hint' => 'Registration Picker Date Time Hint',
			'registration_picker_time_hint' => 'Registration Picker Time Hint',
			'registration_success_prefix' => 'Registration Success Prefix',
			'registration_success_title' => 'Registration Success Title',
			'registration_success_body' => 'Registration Success Body',
			'registration_success_reference' => 'Registration Success Reference',
			'registration_success_back' => 'Registration Success Back',
			'registration_error_title' => 'Registration Error Title',
			'registration_unsupported_fields_semantics' => 'Registration Unsupported Fields Semantics',
			'registration_upload_progress_label' => 'Registration Upload Progress Label',
			'registration_upload_retry_label' => 'Registration Upload Retry Label',
			'resend_code' => 'Resend Code',
			'resend_in_seconds' => 'Resend In Seconds',
			'resending_code_please_wait' => 'Resending Code Please Wait',
			'reset_email_code_required' => 'Reset Email Code Required',
			'reset_password' => 'Reset Password',
			'reset_password_button' => 'Reset Password Button',
			'reset_password_hero' => 'Reset Password Hero',
			'reset_password_intro' => 'Reset Password Intro',
			'reset_password_sms_intro' => 'Reset Password Sms Intro',
			'reset_password_success' => 'Reset Password Success',
			'reset_password_title' => 'Reset Password Title',
			'reset_token_label' => 'Reset Token Label',
			'reset_token_required' => 'Reset Token Required',
			'retry' => 'Retry',
			'save_new_password' => 'Save New Password',
			'save_preferences' => 'Save Preferences',
			'schedule' => 'Schedule',
			'secure_verification_hero' => 'Secure Verification Hero',
			'semantics_loading' => 'Semantics Loading',
			'send_code' => 'Send Code',
			'send_message' => 'Send Message',
			'send_reset_link' => 'Send Reset Link',
			'send_us_a_message' => 'Send Us A Message',
			'sending_code_please_wait' => 'Sending Code Please Wait',
			'settings_intro' => 'Settings Intro',
			'settings_subtitle' => 'Settings Subtitle',
			'settings_title' => 'Settings Title',
			'share' => 'Share',
			'share_copied' => 'Share Copied',
			'share_failed' => 'Share Failed',
			'share_unavailable' => 'Share Unavailable',
			'show_password' => 'Show Password',
			'sign_in' => 'Sign In',
			'sign_in_here' => 'Sign In Here',
			'sign_in_intro' => 'Sign In Intro',
			'sign_in_password_intro' => 'Sign In Password Intro',
			'sign_in_title' => 'Sign In Title',
			'sign_in_with_email' => 'Sign In With Email',
			'sign_in_with_mobile' => 'Sign In With Mobile',
			'sign_in_with_otp' => 'Sign In With Otp',
			'sign_in_with_password' => 'Sign In With Password',
			'sign_out' => 'Sign Out',
			'signing_out' => 'Signing Out',
			'splash_a11y_badge' => 'Splash A11Y Badge',
			'splash_tagline' => 'Splash Tagline',
			'still_need_help' => 'Still Need Help',
			'submit_registration' => 'Submit Registration',
			'submitting_registration_please_wait' => 'Submitting Registration Please Wait',
			'tab_events' => 'Tab Events',
			'tab_library' => 'Tab Library',
			'tab_more' => 'Tab More',
			'tab_radio' => 'Tab Radio',
			'tap_to_update_photo' => 'Tap To Update Photo',
			'terms_of_use' => 'Terms Of Use',
			'text_size' => 'Text Size',
			'text_size_faster' => 'Text Size Faster',
			'text_size_normal' => 'Text Size Normal',
			'text_size_slider_hint' => 'Text Size Slider Hint',
			'text_size_slower' => 'Text Size Slower',
			'unknown' => 'Unknown',
			'unread_notifications_badge_many' => 'Unread Notifications Badge Many',
			'unread_notifications_badge_one' => 'Unread Notifications Badge One',
			'unsupported_fields_notice' => 'Unsupported Fields Notice',
			'update_profile' => 'Update Profile',
			'user_profile' => 'User Profile',
			'user_profile_subtitle' => 'User Profile Subtitle',
			'verification_code_hint' => 'Verification Code Hint',
			'verification_code_label' => 'Verification Code Label',
			'verification_code_required' => 'Verification Code Required',
			'verification_code_resent' => 'Verification Code Resent',
			'verification_incomplete' => 'Verification Incomplete',
			'verify_and_continue' => 'Verify And Continue',
			'verify_button' => 'Verify Button',
			'phone_country_code_semantics' => 'Phone country code semantics',
			'verify_email_intro' => 'Verify Email Intro',
			'verify_email_link' => 'Verify Email Link',
			'verify_email_sent_to' => 'Verify Email Sent To',
			'verify_email_title' => 'Verify Email Title',
			'whats_new_detail_loading' => "What's New Detail Loading",
			'whats_new_empty' => "What's New Empty",
			'whats_new_kind_announcement' => "What's New Kind Announcement",
			'whats_new_kind_community_news' => "What's New Kind Community News",
			'whats_new_kind_in_news' => "What's New Kind In News",
			'whats_new_read_article' => "What's New Read Article",
			'whats_new_read_article_hint' => "What's New Read Article Hint",
			'whats_new_watch_youtube' => "What's New Watch Youtube",
			'verify_identity_hero' => 'Verify Identity Hero',
			'verify_identity_intro' => 'Verify Identity Intro',
			'verify_identity_title' => 'Verify Identity Title',
			'verify_intro' => 'Verify Intro',
			'verify_intro_manual' => 'Verify Intro Manual',
			'verify_title' => 'Verify Title',
			'verifying_code_please_wait' => 'Verifying Code Please Wait',
		);
		return $labels[ $key ] ?? ucwords( str_replace( '_', ' ', $key ) );
	}

	/**
	 * @param string $key Catalog key.
	 * @return string
	 */
	public static function option_name( $key ) {
		return self::OPTION_PREFIX . $key;
	}

	/**
	 * @param string $key Catalog key.
	 * @return bool
	 */
	public static function is_long_text( $key ) {
		$long = array(
			'delete_account_confirm_body' => true,
			'forgot_password_help_body' => true,
			'help_faq_topics' => true,
			'library_youtube_not_configured' => true,
			'profile_info_note' => true,
			'register_a11y_body' => true,
			'unsupported_fields_notice' => true,
		);
		return ! empty( $long[ $key ] );
	}

	/**
	 * Maps legacy OPTION_COPY_* option names to catalog keys.
	 *
	 * @return array<string,string> option_name => catalog_key
	 */
	public static function legacy_option_map() {
		return array(
			'radioudaan_copy_bootstrap_loading' => 'bootstrap_loading',
			'radioudaan_copy_sign_in_intro' => 'sign_in_intro',
			'radioudaan_copy_radio_intro' => 'radio_intro',
			'radioudaan_copy_radio_live_label' => 'radio_live_label',
			'radioudaan_copy_tab_radio' => 'tab_radio',
			'radioudaan_copy_tab_library' => 'tab_library',
			'radioudaan_copy_tab_events' => 'tab_events',
			'radioudaan_copy_tab_about' => 'tab_about',
			'radioudaan_copy_tab_more' => 'tab_more',
			'radioudaan_copy_events_empty' => 'events_empty',
			'radioudaan_copy_library_shows' => 'library_shows',
			'radioudaan_copy_library_whats_new' => 'library_whats_new',
			'radioudaan_copy_verify_intro' => 'verify_intro',
			'radioudaan_copy_submit_registration' => 'submit_registration',
			'radioudaan_copy_registration_success_prefix' => 'registration_success_prefix',
			'radioudaan_copy_library_shows_empty' => 'library_shows_empty',
			'radioudaan_copy_library_whats_new_empty' => 'library_whats_new_empty',
			'radioudaan_copy_unsupported_fields_notice' => 'unsupported_fields_notice',
		);
	}

	/**
	 * @return array<int,string>
	 */
	public static function catalog_keys() {
		return array_keys( self::default_catalog() );
	}
}
