/// Offline fallback copy keyed by WordPress `/config` → `copy` snake_case fields.
/// Product copy is WP-driven; [AppStrings] is the offline catalog only.
const Map<String, String> appCopyDefaults = {
  'about_us': 'About Us',
  'about_us_subtitle': 'Our story and vision',
  'about_whats_new': "What's New",
  'about_whats_new_subtitle': 'Announcements and community news',
  'about_options_intro': '',
  'about_options_title': 'About Radio Udaan',
  'accessibility_section': 'Accessibility',
  'a11y_checked': 'checked',
  'a11y_not_checked': 'not checked',
  'a11y_not_selected': 'not selected',
  'a11y_selected': 'selected',
  'account_delete_failed': 'Could not delete account',
  'account_deleted_signing_out': 'Account deleted. Signing out',
  'account_icon': 'Account',
  'app_logo_semantics': 'Radio Udaan logo',
  'app_name': 'Radio Udaan',
  'back_button': 'Back',
  'back_to_login': 'Back to login',
  'bold_text': 'Bold Text',
  'bold_text_hint': 'Heavier text for easier reading',
  'bootstrap_loading': 'READY TO LAUNCH',
  'bootstrap_offline': 'Could not connect to the server. Check your network and try again.',
  'force_update_title': 'Update required',
  'force_update_message':
      'This version of Radio Udaan is no longer supported. Please update to continue.',
  'force_update_current_build': 'Your current build is {build}.',
  'force_update_button': 'Update app',
  'keyboard_done': 'Done',
  'keyboard_next': 'Next field',
  'call_accessibility_helpline': 'Call Accessibility Helpline',
  'cancel': 'Cancel',
  'close': 'Close',
  'change_password_intro': 'Keep your account secure with a strong password.',
  'change_password_title': 'Change Password',
  'choose_file': 'Choose file',
  'confirm_new_password': 'Confirm New Password',
  'confirm_password_label': 'Confirm password',
  'contact_form_intro': 'Tell us what you need and our team will get back to you.',
  'contact_form_title': 'Send us a message',
  'contact_support': 'Contact Support',
  'contact_title': 'Contact',
  'contact_email_subtitle': 'Send us an email directly',
  'contact_email_title': 'Contact Email',
  'contact_number_subtitle': 'Call our accessibility helpline',
  'contact_number_title': 'Contact Number',
  'copied_to_clipboard': 'Copied to clipboard',
  'copy_value': 'Copy',
  'create_account': 'Create account',
  'current_password': 'Current Password',
  'delete_account': 'Delete account',
  'delete_account_confirm_body': 'This permanently deletes your app login and signs you out. You can sign in again with your phone number.\n\nEvent registrations you already submitted are not removed.',
  'delete_account_confirm_title': 'Delete account?',
  'delete_account_subtitle': 'Removes your app login on our servers. Event registrations are not deleted.',
  'dont_have_account': 'Don\'t have an account?',
  'donate_bank_details_title': 'Bank Account Details',
  'donate_scan_caption': 'Scan the QR code using any UPI app to support Radio Udaan.',
  'donate_scan_title': 'Scan & Donate',
  'donate_us': 'Donate Us',
  'donate_us_subtitle': 'Support our mission online, UPI, or bank transfer',
  'donate_pay_online_title': 'Pay Online',
  'donate_pay_online_subtitle': 'Donate securely with UPI, card, or net banking',
  'donate_amount_custom_label': 'Custom amount (₹)',
  'donate_now_button': 'Donate now',
  'donate_success_title': 'Thank you for your donation',
  'donate_success_message':
      'Your payment was successful. Thank you for supporting Radio Udaan.',
  'donate_failed_message': 'Payment could not be completed. Please try again.',
  'donate_80g_checkbox': 'I want an 80G tax exemption receipt',
  'donate_pan_label': 'PAN (required for 80G receipt)',
  'donate_pan_required': 'Enter a valid PAN to receive your 80G receipt.',
  'donate_form_10be_note':
      'Form 10BE for income tax filing will be issued by the trust as per Income Tax rules.',
  'donate_opening_payment': 'Opening secure payment',
  'donate_check_payment': 'I completed payment',
  'donate_invalid_amount': 'Enter a valid donation amount.',
  'edit_profile_title': 'Edit Profile',
  'email_hint': 'you@example.com',
  'email_invalid': 'Enter a valid email address.',
  'email_label': 'Email',
  'email_not_verified': 'Email not verified',
  'email_support': 'Email Support',
  'event_deep_link_loading': 'Opening event registration',
  'event_registration_title': 'Event Registration',
  'events_empty': 'No open events right now.',
  'events_loading': 'Loading events',
  'events_page_intro': 'Join our vibrant community in upcoming accessible live streams and workshops.',
  'events_page_title': 'Register For Events',
  'events_register_now': 'Register Now',
  'events_register_for_semantics': 'Register For {event_title}',
  'events_registration_closed': 'Registration closed',
  'events_registration_closed_semantics': 'Registration closed for {event_title}',
  'forgot_password_channel_email': 'Email',
  'forgot_password_channel_phone': 'Mobile',
  'forgot_password_email_hint': 'Enter your email',
  'forgot_password_email_note': 'Reset codes are sent only to your verified email. Sign in and verify your email first if you have not already.',
  'forgot_password_help_body': 'Need help? Call our 24/7 accessible support line or use the screen reader shortcut Alt + H.',
  'forgot_password_link': 'Forgot Password?',
  'forgot_password_phone_note': 'We\'ll text a one-time code to your verified mobile number, then you can choose a new password.',
  'forgot_password_title': 'Forgot Password',
  'follow_us': 'Follow us',
  'has_account_link': 'Already have an account? Sign in',
  'has_account_prompt': 'Already have an account?',
  'help_and_contact': 'Contact',
  'help_and_contact_subtitle': 'Send a message to our team',
  'help_message': 'Message',
  'help_search_hint': 'Search FAQ or Support Topics',
  'help_subject': 'Subject',
  'help_title': 'How can we help?',
  'hide_password': 'Hide password',
  'high_contrast_mode': 'High Contrast Mode',
  'identifier_hint': 'you@example.com or mobile number',
  'identifier_label': 'Email or mobile',
  'join_community': 'Join Community',
  'join_the_discussion': 'Join the discussion',
  'join_whats_app_channel': 'Join WhatsApp Channel',
  'label_account_name': 'Account Name',
  'label_account_number': 'Account Number',
  'label_bank_address': 'Address',
  'label_bank_name': 'Bank Name',
  'label_branch_name': 'Branch Name',
  'label_ifsc': 'IFSC Code',
  'label_micr': 'MICR Code',
  'label_upi_id': 'UPI ID',
  'legal_section': 'Legal & account',
  'library_duration_prefix': 'Duration: ',
  'library_loading': 'Loading library',
  'library_open_in_youtube': 'Open in YouTube',
  'library_play_video': 'Play video',
  'library_pause_video': 'Pause video',
  'library_player_native_hint':
      'Use the play and pause buttons below to control the video.',
  'library_player_buffering': 'Video buffering',
  'library_player_paused': 'Video paused',
  'library_playlists': 'Playlists',
  'library_playlists_empty': 'No playlists available yet.',
  'library_saved_screen_title': 'Saved',
  'library_saved_entry_subtitle': 'Your favorite shows and saved videos',
  'library_saved_radio_section': 'Radio shows',
  'library_saved_videos_section': 'Videos',
  'library_saved_empty':
      'Nothing saved yet. Favorite a radio show or save a video to see it here.',
  'library_recent_uploads': 'Recent Uploads',
  'library_recent_uploads_empty': 'No recent uploads yet.',
  'library_save_video': 'Save',
  'library_saved_video': 'Saved',
  'library_search_clear': 'Clear search',
  'library_search_empty': 'No videos match your search.',
  'library_search_hint': 'Type keywords...',
  'library_search_videos': 'Search Videos',
  'library_tap_to_play': 'Tap to play',
  'library_uploaded_hour_ago': '1 hour ago',
  'library_uploaded_just_now': 'Just now',
  'library_uploaded_minute_ago': '1 minute ago',
  'library_uploaded_month_ago': '1 month ago',
  'library_uploaded_week_ago': '1 week ago',
  'library_uploaded_year_ago': '1 year ago',
  'library_uploaded_yesterday': 'Yesterday',
  'library_video_saved': 'Video saved',
  'library_video_unsaved': 'Video removed from saved',
  'library_view_all_playlists': 'View all playlists',
  'library_youtube_attribution': 'Video hosted on YouTube',
  'library_youtube_not_configured': 'Video library is not set up on the server yet. Radio Udaan staff need to add a YouTube API key in WordPress admin.',
  'link_open_failed': 'Could not open link',
  'link_opens_in_browser': 'Opens in browser',
  'link_unavailable': 'This link is not available',
  'login_button': 'Login',
  'login_email_intro': 'Sign in with your email and password.',
  'login_email_verified_note': 'Only verified email addresses can sign in here.',
  'login_mobile_hint': 'Enter your details',
  'login_mobile_intro': 'Sign in with your mobile number and password.',
  'login_mobile_label': 'Mobile Number',
  'login_password_hint': 'Enter your password',
  'login_welcome': 'Welcome back. Let\'s get you listening.',
  'logout': 'Logout',
  'logout_subtitle': 'Securely sign out',
  'made_with_accessibility': 'Made with accessibility in mind',
  'main_navigation': 'Main navigation',
  'message_sent': 'Message sent. Our team will reply soon.',
  'mobile_number_hint': '+91 98765 43210',
  'mobile_number_label': 'Mobile number',
  'more_options_intro': '',
  'more_options_title': 'More Options',
  'name_label': 'Full Name',
  'name_required': 'Enter your name.',
  'new_password': 'New Password',
  'no_account_link': 'Create an account',
  'not_signed_in': 'Not signed in',
  'notification_read': 'Read',
  'notification_unread': 'Unread',
  'notification_time_just_now': 'Just now',
  'notification_time_minute_ago': '1 minute ago',
  'notification_time_minutes_ago': '{count} minutes ago',
  'notification_time_hour_ago': '1 hour ago',
  'notification_time_hours_ago': '{count} hours ago',
  'notification_time_yesterday': 'Yesterday',
  'notification_time_days_ago': '{count} days ago',
  'notifications_mark_all_read': 'Mark all as read',
  'notifications_marked_all': 'All notifications marked as read',
  'notifications_empty': 'No notifications yet.',
  'notifications_filter_all': 'All',
  'notifications_filter_unread': 'Unread',
  'notifications_loading': 'Loading notifications',
  'notifications_section': 'Notifications',
  'push_register_device': 'Register this iPhone for alerts',
  'push_register_device_hint': 'Use if alerts are not arriving after you allowed notifications',
  'push_register_success': 'This device is registered for push alerts',
  'push_register_permission_denied': 'Notifications are blocked. Open iPhone Settings, Radio Udaan, and turn on Allow Notifications.',
  'push_register_token_failed': 'Could not get a push token. Check that the APNs key is uploaded in Firebase Console.',
  'push_register_api_failed': 'Could not save this device on the server. Check your connection and try again.',
  'push_register_unavailable': 'Push registration is not available on this device.',
  'notifications_subtitle': 'Alerts and updates',
  'notifications_title': 'Notifications',
  'notifications_unread_empty': 'No unread notifications.',
  'notification_permission_title': 'Stay connected to Radio Udaan',
  'notification_permission_body':
      'Allow notifications for live radio controls on your lock screen, plus alerts about events and station updates. You can change this anytime in Settings. Radio will still play if you choose Not now.',
  'notification_permission_continue': 'Continue',
  'notification_permission_not_now': 'Not now',
  'notify_event_alerts': 'Event Alerts',
  'notify_live_broadcasts': 'Live Broadcasts',
  'notify_promotions': 'Promotions',
  'otp_enter_title': 'Enter OTP',
  'otp_having_trouble': 'Having trouble?',
  'otp_label': 'Verification code',
  'otp_login_button': 'LOGIN',
  'otp_pin_row_empty': 'Empty',
  'otp_pin_row_label': 'Verification code',
  'otp_resend_label': 'Resend OTP',
  'otp_send_code': 'Send code',
  'otp_wait_prompt': 'Didn\'t receive the code? Wait ',
  'password_hidden_announce': 'Password hidden',
  'password_label': 'Password',
  'password_mismatch': 'Passwords do not match.',
  'password_required': 'Enter your password.',
  'password_shown_announce': 'Password shown',
  'phone_country_search_hint': 'Search country',
  'phone_country_picker_title': 'Select country code',
  'phone_country_favorites': 'Favorites',
  'phone_field_helper': 'Choose your country code, then enter your mobile number without the leading zero.',
  'phone_field_label': 'Mobile number',
  'phone_national_hint': '98765 43210',
  'preferences_saved': 'Preferences saved',
  'privacy_policy': 'Privacy policy',
  'profile': 'Profile',
  'profile_info_note': 'Your mobile number is fixed to your login. If you change your email, we send a verification code to the new address.',
  'profile_updated': 'Profile updated successfully',
  'radio_connecting': 'Connecting…',
  'radio_favorite': 'Favorite',
  'radio_favorite_add': 'Add to favorites',
  'radio_favorite_remove': 'Remove from favorites',
  'radio_intro': ' ',
  'radio_pause': 'Pause',
  'radio_play': 'Play Live Stream',
  'radio_play_on_air': 'Play Live Stream. On air: {show}',
  'radio_playback_error': 'Could not play live radio',
  'radio_playing': 'Live radio is playing',
  'radio_schedule_empty': 'No schedule available right now.',
  'radio_schedule_on_air': 'On air now',
  'radio_schedule_repeat': 'Repeat',
  'radio_schedule_title': 'Radio schedule',
  'radio_share_live': 'Share live',
  'radio_share_text_fallback': 'Get the Radio Udaan app — community radio by and for persons with disabilities.',
  'radio_show_subtitle': ' ',
  'radio_show_title': 'Udaan Morning Show',
  'radio_stop': 'Stop Live Stream',
  'radio_stopped': 'Live radio stopped',
  'radio_upcoming_none': 'No upcoming segments found.',
  'radio_upcoming_segments': 'Upcoming segments',
  'radio_view_full_schedule': 'View full schedule',
  'radio_volume': 'Volume',
  'radio_volume_slider_hint':
      'Adjustable slider. Swipe up to increase or down to decrease in ten percent steps. You can also drag the track left or right.',
  'radio_volume_announce': 'Volume, {percent} percent',
  'radio_whatsapp_url_fallback': '#',
  'radio_with_hosts_prefix': 'with ',
  'reduce_motion': 'Reduce Motion',
  'reduce_motion_hint': 'Limit animations in the app',
  'register_a11y_body': 'This form is optimized for screen readers and keyboard navigation. Large touch targets (64px+) and high contrast (4.5:1+) are enabled. Use Tab to move between fields.',
  'register_a11y_title': 'Accessibility Assist',
  'register_button': 'Register',
  'register_confirm_hint': 'Repeat your password',
  'register_here': 'Register Here',
  'register_intro': 'Join our inclusive community and experience accessible radio like never before.',
  'register_mobile_hint': '98765 43210',
  'register_name_hint': 'Enter your full name',
  'register_password_hint': 'Min. 8 characters',
  'register_title': 'Create Account',
  'registration_field_required': 'This field is required.',
  'registration_no_file_selected': 'No file selected',
  'resend_code': 'Resend code',
  'reset_password': 'Reset password',
  'reset_password_button': 'Reset Password',
  'reset_password_hero': 'Reset password',
  'reset_password_intro': 'Choose a new password.',
  'reset_password_title': 'Reset password',
  'reset_token_label': 'Reset link token',
  'reset_token_required': 'Enter the reset link token from your email.',
  'retry': 'Retry',
  'save_new_password': 'Save New Password',
  'save_preferences': 'Save Preferences',
  'schedule': 'Schedule',
  'secure_verification_hero': 'Secure verification',
  'semantics_loading': 'Loading…',
  'send_code': 'Send code',
  'send_message': 'Send Message',
  'send_reset_link': 'Send reset instructions',
  'send_us_a_message': 'Send us a message',
  'sending_code_please_wait': 'Sending code, please wait',
  'settings_intro': 'Customize your accessibility and notification preferences.',
  'settings_subtitle': 'Accessibility and notifications',
  'settings_title': 'Settings',
  'share': 'Share',
  'share_copied': 'Share message copied to clipboard',
  'share_failed': 'Could not open share sheet',
  'share_unavailable': 'Sharing is not available on this device',
  'show_password': 'Show password',
  'sign_in': 'Sign in',
  'sign_in_here': 'Sign In here',
  'sign_in_intro': 'Choose your country code and mobile number. We will send a one-time code by SMS.',
  'sign_in_password_intro': 'Sign in with your email or mobile number and password.',
  'sign_in_title': 'Sign in',
  'sign_in_with_email': 'Login using email',
  'sign_in_with_mobile': 'Login using mobile',
  'sign_in_with_otp': 'Login with OTP',
  'sign_in_with_password': 'Sign in with password',
  'sign_out': 'Sign out',
  'signing_out': 'Signing out',
  'splash_a11y_badge': 'Optimized for screen readers',
  'splash_tagline': '...A flight of life',
  'still_need_help': 'Still need help?',
  'submit_registration': 'Submit Registration',
  'tab_about': 'About',
  'tab_events': 'Events',
  'tab_library': 'Library',
  'tab_more': 'More',
  'tab_radio': 'Live Radio',
  'tap_to_update_photo': 'Tap to update photo',
  'terms_of_use': 'Terms of use',
  'text_size': 'Text Size',
  'text_size_faster': 'Larger',
  'text_size_normal': 'Normal',
  'text_size_slower': 'Smaller',
  'unknown': 'Unknown',
  'unsupported_fields_notice': 'Some fields on this form are not supported in the app yet. Contact Radio Udaan if you need help completing them.',
  'update_profile': 'Update Profile',
  'user_profile': 'User Profile',
  'user_profile_subtitle': 'Update your information',
  'verification_code_label': 'Verification code',
  'verify_and_continue': 'Verify and continue',
  'verify_button': 'Verify',
  'verify_email_link': 'Verify email',
  'verify_email_title': 'Verify email',
  'whats_new_detail_loading': 'Loading update',
  'whats_new_empty': 'No updates yet.',
  'whats_new_kind_announcement': 'Announcement',
  'whats_new_kind_community_news': 'Community News',
  'whats_new_kind_in_news': 'In the News',
  'whats_new_read_article': 'Read article',
  'whats_new_read_article_hint': 'Opens the news article in your browser',
  'whats_new_watch_youtube': 'Watch on YouTube',
  'verify_identity_hero': 'Verify your identity',
  'verify_identity_intro': 'We\'ve sent a 6-digit security code to your registered mobile number ending in',
  'verify_identity_title': 'Verify Identity',
  'verify_intro': 'Enter the code sent to your number. Type the digits manually — the app does not read SMS.',
  'verify_title': 'Verify code',
  'verifying_code_please_wait': 'Verifying code, please wait',
  'resend_in_seconds': 'Resend in {seconds}s',
  'verify_email_sent_to': 'We sent a 6-digit code to {email}.',
  'branding_logo_semantics': '{app_name} logo',
  'otp_pin_row_sms_hint': 'Enter {length} digits from your SMS',
  'otp_pin_row_email_hint': 'Enter {length} digits from your email',
  'otp_pin_row_value': '{code} entered',
  'password_min_hint': 'Min. {min_length} characters',
  'reset_password_sms_intro': 'Choose a new password for {phone}.',
  'profile_signed_in_semantics': '{profile}, signed in as {details}',
  'phone_country_code_semantics':
      'Country code, {country_name}, plus {dial_code}. Double tap to change country.',
  'event_deep_link_opening': 'Opening registration for {event_title}',
  'radio_favorite_add_label': 'Add {show_title} to favorites',
  'radio_favorite_remove_label': 'Remove {show_title} from favorites',
  'radio_favorite_added': 'Added {show_title} to favorites',
  'radio_favorite_removed': 'Removed {show_title} from favorites',
  'registration_none_selected': 'None selected',
  'app_version_label': 'Radio Udaan Version {version}',
  'profile_email_semantics': 'Email {email}. Cannot be changed.',
  'profile_mobile_semantics': 'Mobile number {phone}. Cannot be changed.',
  'unread_notifications_badge_one': '1 unread notification',
  'unread_notifications_badge_many': '{count} unread notifications',
  'radio_live_label': 'Live now',
  'library_shows': 'Playlists',
  'library_whats_new': 'Recent Uploads',
  'library_shows_empty': 'No playlists available yet.',
  'library_whats_new_empty': 'No recent uploads yet.',
  'event_registration_loading_form': 'Loading registration form',
  'event_registration_retry_load': 'Retry loading registration form',
  'forgot_password_channel_semantics': 'Choose email or mobile for password reset',
  'forgot_password_intro': 'Reset your password using your email or mobile number.',
  'forgot_password_success': 'If an account exists, reset instructions have been sent.',
  'high_contrast_mode_hint': 'Maximize visibility of interface elements',
  'identifier_invalid': 'Enter a valid email address or mobile number.',
  'library_embed_error': 'This video could not play inside the app. Try opening it in YouTube.',
  'library_no_description': 'No description available for this video.',
  'library_no_video': 'This video cannot be played in the app right now.',
  'library_playlist_videos_empty': 'This playlist has no videos yet.',
  'otp_code_incomplete': 'Enter the full code from your SMS.',
  'otp_digit_hint': 'Enter all digits from the SMS; up to 8 digits',
  'otp_resent_success': 'A new code has been sent. Check your SMS.',
  'otp_sent_intro': 'We have sent a 6-digit code to your mobile number',
  'password_changed_sign_in_again': 'Password changed. Please sign in again.',
  'password_requirements_not_met': 'Please meet all password requirements.',
  'password_too_short': 'Password is too short. Check the minimum length in settings.',
  'phone_field_hint': 'International mobile with country code, e.g. +91 98765 43210 or +1 555 123 4567',
  'phone_invalid': 'Enter a valid mobile number for the country you selected.',
  'phone_national_field_semantics': 'Mobile number without country code',
  'preferences_discarded': 'Unsaved preference changes discarded',
  'preferences_save_failed': 'Could not save preferences. Try again.',
  'profile_email_locked_hint': 'Linked to your account. Cannot be changed here.',
  'profile_email_verification_sent': 'Verification code sent to your new email. Enter the code on the next screen.',
  'profile_email_verify_needed':
      'Email updated. Open Verify email and tap Send code when you are ready.',
  'profile_mobile_locked_hint': 'Linked to your login. Cannot be changed here.',
  'radio_audio_unavailable': 'Live radio could not start on this device. Check your internet connection and try Play again.',
  'radio_schedule_failed': 'Could not load the schedule. Please try again.',
  'radio_schedule_station_time_label': '{station_time} IST',
  'radio_schedule_dual_time_label': '{station_time} IST · {local_time} your time',
  'radio_stream_missing': 'Stream URL is not configured on the server.',
  'register_copyright': '© 2024 Radio Udaan - Voice of Empowerment',
  'registration_account_locked_hint': 'From your account, cannot edit.',
  'registration_address_hint': 'Street, city, state, postal code',
  'registration_incomplete': 'Registration could not be completed.',
  'registration_picker_date_hint': 'Double tap to choose date',
  'registration_picker_date_time_hint': 'Double tap to choose date and time',
  'registration_picker_time_hint': 'Double tap to choose time',
  'registration_previous_page': 'Previous',
  'registration_next_page': 'Next',
  'registration_page_label': 'Page {current} of {total}',
  'registration_success_prefix': 'Registration submitted successfully. Reference: entry',
  'registration_success_title': 'Registration submitted',
  'registration_success_body':
      'Thank you. We received your registration for {event_title}.',
  'registration_success_reference': 'Reference number: {entry_id}',
  'registration_success_back': 'Back to events',
  'registration_error_title': 'Could not submit registration',
  'resending_code_please_wait': 'Sending a new code, please wait',
  'reset_email_code_required': 'Enter the 6-digit code from your email.',
  'reset_password_success': 'Password updated. You can sign in now.',
  'submitting_registration_please_wait': 'Submitting registration, please wait',
  'text_size_slider_hint': 'Drag to adjust text size from smaller to larger',
  'verification_code_hint': 'Enter the 6-digit code from your email.',
  'verification_code_required': 'Enter the 6-digit verification code.',
  'verification_code_resent': 'A new verification code has been sent.',
  'verification_incomplete': 'Verification did not complete. Try again.',
  'verify_dev_hint': 'Development build: code may be prefilled from the server.',
  'verify_email_intro': 'Enter the 6-digit code we sent to your email.',
  'verify_email_send_prompt':
      'Tap "Send code" to get a 6-digit verification code by email.',
};
